#!/bin/bash

echo $1

cd $1

if command -v gfortran
then
    gfortran -o mercury6 mercury6_3.for
    gfortran -o element6 element6.for
    gfortran -o close6 close6.for 

elif command -v g77
then
    g77 -o mercury6 mercury6_3.for
    g77 -o element6 element6.for
    g77 -o close6 close6.for   
else
    echo "Mercury6 needs some form of fortran compiler to run"
    exit 1
fi

./mercury6 >> condor.stdout

rm out_encounters.txt
