#!/usr/bin/env python

import os
import sys
import smtplib
import subprocess
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

folder = sys.argv[1]
os.chdir(folder)

if sys.platform.startswith('linux'):
    p = subprocess.Popen(['make'])
elif sys.platform == 'darwin':
    p = subprocess.Popen(['make', 'osx'])
else:
    sys.exit('FAILURE to compile!')

p.communicate()
p.wait()


p = subprocess.Popen(['./mercury6'])
p.communicate()
p.wait()

if os.path.exists('out_encounters.txt'):
    os.remove('out_encounters.txt')

